config/routes.rb
Pip48rails::Application.routes.draw do

  get "leaderboard/index"

  get 'about' => 'pages#about'
  get 'schedule' => 'pages#schedule'
  get 'map' => 'pages#map'
  
  match 'leaderboard/:action', :controller => 'leaderboard'

  
  resources :clans do 
    resources :ninjas
  end

  root :to => 'pages#index'

end

app/models/ninja.rb
class Ninja < ActiveRecord::Base
  attr_accessible :clan_id, :desc, :fb, :name, :tw, :img, :x, :y
  belongs_to :clan
 
  def profile_image_url
    Rails.cache.fetch("profile_image_url_#{self.id}", :expires_in => 12.hours) do
      if !self.img.blank?
        img
      elsif !self.fb.blank?
        Koala::Facebook::API.new.get_picture(self.fb)
      elsif !self.tw.blank?
        Twitter.user(self.tw).profile_image_url()
      end
    end
  end
  
end

app/controllers/ninjas_controller.rb
class NinjasController < ApplicationController

  before_filter :authenticate

  # GET /ninjas
  # GET /ninjas.json
  def index
    @clan = params[:clan_id]
    @ninjas = Ninja.find_all_by_clan_id(@clan)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ninjas }
    end
  end

  # GET /ninjas/1
  # GET /ninjas/1.json
  def show
    @clan = params[:clan_id]
    @ninja = Ninja.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ninja }
    end
  end

  # GET /ninjas/new
  # GET /ninjas/new.json
  def new
    @clan = params[:clan_id]
    @ninja = Ninja.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ninja }
    end
  end

  # GET /ninjas/1/edit
  def edit
    @clan = params[:clan_id]
    @ninja = Ninja.find(params[:id])
  end

  # POST /ninjas
  # POST /ninjas.json
  def create
    @clan = params[:clan_id]
    @ninja = Ninja.new(params[:ninja])

    respond_to do |format|
      if @ninja.save
        format.html { redirect_to clan_ninja_path(@clan, @ninja), notice: 'Ninja was successfully created.' }
        format.json { render json: @ninja, status: :created, location: @ninja }
      else
        format.html { render action: "new" }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ninjas/1
  # PUT /ninjas/1.json
  def update
    @clan = params[:clan_id]
    @ninja = Ninja.find(params[:id])

    respond_to do |format|
      if @ninja.update_attributes(params[:ninja])
        format.html { redirect_to clan_ninja_path(@clan, @ninja), notice: 'Ninja was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninjas/1
  # DELETE /ninjas/1.json
  def destroy
    @ninja = Ninja.find(params[:id])
    @ninja.destroy

    respond_to do |format|
      format.html { redirect_to ninjas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ninjas_helper.rb
module NinjasHelper
end

app/views/ninjas/_form.html.haml
- @ninja.persisted? ? url = clan_ninja_path(@clan, @ninja) : url = clan_ninjas_path(@clan)
= form_for @ninja, url: url do |f|
  - if @ninja.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ninja.errors.count, "error")} prohibited this ninja from being saved:"
      %ul
        - @ninja.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :tw
    = f.text_field :tw
  .field
    = f.label :fb
    = f.text_field :fb
  .field
    = f.label :img
    = f.url_field :img
  .field
    = f.label :x
    = f.text_field :x
  .field
    = f.label :y
    = f.text_field :y
  .field
    = f.label :desc
    = f.text_field :desc
  .field
    = f.hidden_field :clan_id, value: @clan
  .actions
    = f.submit 'Save'

app/views/ninjas/edit.html.haml
%h1 Editing ninja

= render 'form'

= link_to 'Show', clan_ninja_path(@clan, @ninja)
\|
= link_to 'Back', clan_ninjas_path(@clan)

app/views/ninjas/index.html.haml
%h1 Listing ninjas

= @clan

%table
  %tr
    %th Name
    %th Tw
    %th Fb
    %th Desc
    %th Clan
    %th
    %th
    %th

  - @ninjas.each do |ninja|
    %tr
      %td= ninja.name
      %td= ninja.tw
      %td= ninja.fb
      %td= ninja.desc
      %td= ninja.clan_id
      %td= link_to 'Show', clan_ninja_path(@clan, ninja)
      %td= link_to 'Edit', edit_clan_ninja_path(@clan, ninja)
      %td= link_to 'Destroy', clan_ninja_path(@clan, ninja), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Ninja', new_clan_ninja_path(@clan)

app/views/ninjas/new.html.haml
%h1 New ninja

= render 'form'

= link_to 'Back', clan_ninjas_path(@clan)

app/views/ninjas/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ninja.name
%p
  %b Tw:
  = @ninja.tw
%p
  %b Fb:
  = @ninja.fb
%p
  %b Img:
  = @ninja.img
%p
  %b Desc:
  = @ninja.desc
%p
  %b Clan:
  = @ninja.clan_id

= link_to 'Edit', edit_clan_ninja_path(@clan, @ninja)
\|
= link_to 'Back', clan_ninjas_path(@clan)