config/routes.rb
Pip48rails::Application.routes.draw do

  get "leaderboard/index"

  get 'about' => 'pages#about'
  get 'schedule' => 'pages#schedule'
  get 'map' => 'pages#map'
  
  match 'leaderboard/:action', :controller => 'leaderboard'

  
  resources :clans do 
    resources :ninjas
  end

  root :to => 'pages#index'

end

app/models/clan.rb
class Clan < ActiveRecord::Base
  attr_accessible :ensign, :name
  has_many :ninjas

end

app/controllers/clans_controller.rb
class ClansController < ApplicationController

  before_filter :authenticate, :except => [:index]

  # GET /clans
  # GET /clans.json
  def index    
    @clans = Clan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clans }
    end
  end

  # GET /clans/1
  # GET /clans/1.json
  def show
    @clan = Clan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clan }
    end
  end

  # GET /clans/new
  # GET /clans/new.json
  def new
    @clan = Clan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clan }
    end
  end

  # GET /clans/1/edit
  def edit
    @clan = Clan.find(params[:id])
  end

  # POST /clans
  # POST /clans.json
  def create
    @clan = Clan.new(params[:clan])

    respond_to do |format|
      if @clan.save
        format.html { redirect_to @clan, notice: 'Clan was successfully created.' }
        format.json { render json: @clan, status: :created, location: @clan }
      else
        format.html { render action: "new" }
        format.json { render json: @clan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clans/1
  # PUT /clans/1.json
  def update
    @clan = Clan.find(params[:id])

    respond_to do |format|
      if @clan.update_attributes(params[:clan])
        format.html { redirect_to @clan, notice: 'Clan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clans/1
  # DELETE /clans/1.json
  def destroy
    @clan = Clan.find(params[:id])
    @clan.destroy

    respond_to do |format|
      format.html { redirect_to clans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clans_helper.rb
module ClansHelper
end

app/views/clans/_form.html.haml
= form_for @clan do |f|
  - if @clan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@clan.errors.count, "error")} prohibited this clan from being saved:"
      %ul
        - @clan.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :ensign
    = f.text_field :ensign
  .actions
    = f.submit 'Save'

app/views/clans/edit.html.haml
%h1 Editing clan

= render 'form'

= link_to 'Show', @clan
\|
= link_to 'Back', clans_path

app/views/clans/index.html.haml
%section.participants
  %header=t '.clans_title'

  - @ninjas = %w(sword ruby kick crouched)
  
  - @clans.each do |clan|
    %article
      %header= clan.name
      
      %ul
        - clan.ninjas.each do |ninja| 
          %li
            - n = @ninjas[rand(@ninjas.size)]
            = image_tag "ninjas/ninja_#{n}.png", class: "ninja #{n}"
            .face{style: "background-image: url(#{ninja.profile_image_url}); background-position: #{ninja.x}px #{ninja.y}px"}
              
            %br/
            = ninja.name
            
            - if !ninja.tw.blank?
              %br/
              %small 
                [ follow
                = link_to "@#{ninja.tw}", "http://twitter.com/#{ninja.tw}" 
                ]

app/views/clans/new.html.haml
%h1 New clan

= render 'form'

= link_to 'Back', clans_path

app/views/clans/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @clan.name
%p
  %b Ensign:
  = @clan.ensign

= link_to 'Add ninja', new_clan_ninja_path(@clan)
\|
= link_to 'Edit', edit_clan_path(@clan)
\|
= link_to 'Back', clans_path