config/routes.rb
Pip48rails::Application.routes.draw do

  get "leaderboard/index"

  get 'about' => 'pages#about'
  get 'schedule' => 'pages#schedule'
  get 'map' => 'pages#map'
  
  match 'leaderboard/:action', :controller => 'leaderboard'

  
  resources :clans do 
    resources :ninjas
  end

  root :to => 'pages#index'

end

app/views/layouts/_countdown.html.haml
.countdown
  .number#d10
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom

  .number#d1.space
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom          
  
  .number#h10
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom

  .number#h1.space
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom

  .number#m10
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom

  .number#m1.space
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom

  .number#s10
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom

  .number#s1
    .flip
      .front
      .back
    .fixed.top
    .fixed.bottom
    
  %p=t 'layout.days'
  %p=t 'layout.hours'
  %p=t 'layout.minutes'
  %p=t 'layout.seconds' 

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title=t 'layout.title'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag

    - if Rails.env.production?
      :javascript

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-34709010-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();



  %body.animations
    %nav{role: 'navigation'}
      %ul
        %li= link_to 'Home', root_path
        %li= link_to t('pages.index.participants'), clans_path
        %li= link_to t('layout.schedule'), schedule_path
        %li= link_to t('layout.map'), map_path
        %li.date=t 'layout.when'

    %section{role: 'header'}
      %header
        %h1
          =image_tag 'ninja_logo.png', class: 'ninja'
          %span._4.animated> 4
          %span._8> 8
          %span._rails> rails
          =image_tag 'sold_out.png', class: 'sold_out'


      %h2.pitch
        %small=t 'layout.when'
        %br/
        =t 'layout.pitch'


      %section.timeline

        %div
          %article.current.past
            %header=t 'layout.registration_48rails_date_html'
            %p=t 'layout.registration_48rails_what_html'


          %article.current
            %header=t 'layout.registration_railsrumble_date_html'
            %p=t 'layout.registration_railsrumble_what_html'

          %article.future
            %header=t 'layout.hack_date_html'
            %p=t 'layout.hack_what_html'

    %section{role: 'main', class: "#{controller.controller_name}_#{controller.action_name}"}
      %div
        = yield


    %footer
      = render 'layouts/countdown'


      %div

        %article.third
          %header About
          %p
            = image_tag 'dexter.png', class: 'dexter'
            %b 48 rails&nbsp;
            =t 'layout.a_project_by'
            &nbsp;
            %a{href: 'http://www.programmersinpadua.it', target: '_blank'}> Programmers in Padua
            ,
            =t 'layout.pip_pitch'

          %ul
            %li
              %a{href: 'http://twitter.com/brigugraphic', target: '_blank'} @brigugraphic
              &ndash; graphic ninja
            %li
              %a{href: 'http://twitter.com/ogeidix', target: '_blank'} @ogeidix
              &ndash; west coast ninja
            %li
              %a{href: 'http://twitter.com/pigatss', target: '_blank'} @pigatss
              &ndash; organization ninja
            %li
              %a{href: 'http://twitter.com/realfuzzy', target: '_blank'} @realfuzzy
              &ndash; rails ninja


        %article.third

          %header=t 'layout.contact_us'
          %p
            =t 'layout.email_us_at'
            %a{href: 'mailto:ninja@48rails.it'} ninja@48rails.it

          %p
            =t 'layout.tweet_us_at'
            %a{href: 'http://twitter.com/48rails', target: '_blank'} @48rails

          %p=t 'layout.staff_call'

        %article.third


    %p#lang_selector
      - if I18n.locale == :it
        = image_tag 'italian.png', lang: 'it', class: 'selected'
        %a{href: "#{request.url.gsub(/\?lang=[a-z]{2}/,'')}?lang=en", title: 'switch to English', lang: 'en'}
          = image_tag 'english.png', lang: 'en'


      - else
        %a{href: "#{request.url.gsub(/\?lang=[a-z]{2}/,'')}?lang=it", title: 'passa all\'Italiano', lang: 'it'}
          = image_tag 'italian.png', lang: 'it'
        = image_tag 'english.png', lang: 'en', class: 'selected'

app/views/layouts/leaderboard.html.haml
!!!5
%html
  %head
    %title=t 'layout.title'
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'leaderboard'
    = javascript_include_tag 'application'
    = javascript_include_tag 'leaderboard'
    = csrf_meta_tags
    = favicon_link_tag           
    - if Rails.env.production?
      :javascript

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-34709010-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    
  %body
    = yield